Desing additions
projeto-v3l0z/V3L0Z pull request #1
Opened 2023-02-22 13:42 UTC by leon-rdo

### Fork for Design Additions
**Contribuitions:**
* Project organized in folders;
* Visual identity created;
* Lorem `index.html` created;
* Color theme defined;

**Observation:** To use a `.scss` file, you must install the addon _**"Live SASS Compiler"**_ and define the _savePath_ as _`/src/public/styles/css`_ in `settings.json`.

2023-02-22 16:28 UTC, Kevin-Sarges requested changes

2023-02-22 16:28 UTC, Kevin-Sarges commented on src/public/styles/scss/style.scss
> +$Color-5: #0d0d0d;
- sempre que você for criar uma variável nunca coloque com maiúsculas.
- eu recomendo você usar o nome da propria cor mesmo Ex: `$blue01` caso tenha só um tipo de varição de cor basta colocar no nome da cor mesmo EX: `white`

2023-02-22 16:28 UTC, Kevin-Sarges commented on src/public/styles/css/style.css
> +  background-color: #f2ddd0;
- adicione essa cor às variáveis.

2023-02-22 16:28 UTC, Kevin-Sarges commented on src/public/styles/css/style.css
> +  background-image: linear-gradient(43deg, #4158d0 0%, #c850c0 46%, #ffcc70 100%);
- adicione essa cor às variáveis.

2023-02-22 16:28 UTC, Kevin-Sarges commented on src/public/styles/scss/style.scss
> +}
- crie um arquivo chamado `_default-styles.scss` para ficar essa parte de estilização do `body`, `footer` e `#dev` que você fez.

2023-02-22 16:42 UTC, Kevin-Sarges commented
crie uma arquivo `main.scss` para ficar as importações dos outros arquivos scss.

2023-02-23 18:37 UTC, leon-rdo commented
# Corrections
* Distinct file for the variables created: `_variables.scss`;
* Variables names enhanced;
* Background color now is a variable: `$blue`;
* Distinct file created for the defalt styles of the page: `_defalt-styles`;
* Distinct files are imported to the new file: `main.scss`;

Changes required by: @Kevin-Sarges.
Aplyed on [this branch](https://github.com/Kevin-Sarges/landing-page-veloz/pull/1/commits/4e707da14603bb2d62d38ad46931e9cee6b237c4).

2023-02-23 18:40 UTC, leon-rdo commented
## More Corrections
* main.scss compiled into `main.css`;
* Path fixed from the file `style.css` to the file `main.css` on `index.html`;
* ` lang="en"` fixed to `lang="pt-br"` on `index.html`;

Changes aplyed on [this branch](https://github.com/Kevin-Sarges/landing-page-veloz/pull/1/commits/d7c3a067792c72ac92cf4223a760ce577df24052).

2023-02-23 18:46 UTC, Kevin-Sarges approved these changes

2023-02-23 18:47 UTC, merged